### ISSUE TITLE
file not founnd

### ISSUE THREAD

**Issue by Scout-UCAS** [sbelharbi/deep-active-learning-for-joint-classification-and-segmentation-with-weak-annotator#2]
Thanks for your outstanding work, but when I run the code, some error occurs,
FileNotFoundError: [Errno 2] No such file or directory: '/home/ps/Downloads/act/active_segmentation/exps/paper_label_prop/gl                           as/Entropy/id_03_23_2022_10_10_44_144656__484070-task_SEGMENTATION-subtask_Classification_Segmentation-al_Entropy-ds_glas-se                           ed_1/common/train_1.csv'

**Comment by Scout-UCAS** [comment]
/home/ps/Downloads/act/active_segmentation is the root path

**Comment by sbelharbi** [comment]
hi,
it seems that you are trying to run an active learning round while the previous rounds are not done yet.
the folder `common` should be something like this
![common-folder](https://user-images.githubusercontent.com/23446793/159715791-befbccfd-6d8a-4dde-809c-834ed4290ef2.png)

can you post the command that you are trying to run that generates the error?

also, root path is supposed to point to folder that contains folders where each one contains a dataset.
according to your description, root path points to the absolute path of the code folder where exps folder is located.
see here https://github.com/sbelharbi/deep-active-learning-for-joint-classification-and-segmentation-with-weak-annotator/blob/9192182b9a924735371c7525beb6319ed4119f2f/tools.py#L2838

thanks

**Comment by Scout-UCAS** [comment]
Thanks for your timely reply, I  write the wrong root path.
Now, it works
.
